### ISSUE TITLE
__clang_analyzer__ for clangd

### ISSUE THREAD

**Issue by calewis** [kokkos/llvm-project#10]
Enable the `__clang_analyzer__` definition for clangd.  I'm not sure this is really the correct thing to do, but as we have things set up now it is the only way to get `ensure-kokkos-function` to work correctly with clangd.  

This is because Kokkos only annotates `KOKKOS_.*FUNCITON` when the `__clang_analyzer__` definition is detected. 

I think a longer term solution is to add something like `__kokkos_analyzer__` to clangd/clang-tidy so that we know we are in a context that Kokkos definitions should be modified. 

@DavidPoliakoff thoughts

**Comment by DavidPoliakoff** [comment]
@calewis : I like both sides of this. It's a good short term solution (enabling in `clangd`), but yeah, we might want a long-term answer too.

Good thinking

**Comment by calewis** [comment]
Closing this for now, if/when we decide that we need a kokkos specific compiler defined macro we will make one.
